/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cj.dao.ContentDescDao;
import com.yourcompany.struts.form.ContentDescForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-10-2009
 * 
 * XDoclet definition:
 * @struts.action path="/contentDescrip" name="contentDescForm" input="/form/contentDesc.jsp" parameter="method" scope="request" validate="true"
 */
public class ContentDescAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward contentDesc(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ContentDescForm contentDescForm = (ContentDescForm) form;
		
		PrintWriter pw=null;
		try {
			pw=response.getWriter();
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		
		String fileName=contentDescForm.getFileName();
		String fileDesc=contentDescForm.getFileDesc();
		ContentDescDao cdd=new ContentDescDao();
		boolean b=cdd.contentDesc(fileName, fileDesc);
		if(b){
			pw.print("success");
		}else
		pw.print("failure");
		
		
		
		return null;
	}
}
