/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.io.DataInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.ServletInputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cj.dao.ContentDescDao;
import com.yourcompany.struts.form.ContentDescForm;
import com.yourcompany.struts.form.ImageActionForm;
import com.yourcompany.struts.form.VideoUploadForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-18-2009
 * 
 * XDoclet definition:
 * @struts.action path="/imageAction" name="imageActionForm" input="/form/imageAction.jsp" parameter="method" scope="request" validate="true"
 */
public class ImageAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		ImageActionForm imageActionForm = (ImageActionForm) form;
		ContentDescForm contentDescForm = (ContentDescForm) form;
		
		//DataInputStream  dataInputStream =null;
		
		//CLIENT WILL SEND EVEN THE CATEGORY AS PARAMETER..
		//
		System.out.println("Image upload action");
		
		PrintWriter pw=null;
		try {
			pw=response.getWriter();
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		
		String fileName=contentDescForm.getFileName();
		String fileDesc=contentDescForm.getFileDesc();
		ContentDescDao cdd=new ContentDescDao();
		boolean b=cdd.contentDesc(fileName, fileDesc);
		if(b){
			pw.print("success");
		}else
		pw.print("failure");
		
		
		
		//InputStream inputStream;
		try {
			System.out.println("IN ACTION CLASS.....");
			ServletInputStream inputStream = request.getInputStream();
			SimpleDateFormat sdf=new SimpleDateFormat("dd MMM yy hh mm ss");
			String fileLocation="images\\"+fileName+sdf.format(new Date())+".PNG";
			FileOutputStream fos=new FileOutputStream("..\\webapps\\CJ\\"+fileLocation);
			int i=0;
			while((i=inputStream.read())!=-1)
			{
				fos.write(i);
					
			}
			fos.flush();
			fos.close();
			System.out.println("File Created... Successfully...");
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		
		return null;
	}
}