/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.ServletInputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cj.dao.ContentDescDao;
import com.yourcompany.struts.form.ContentDescForm;
import com.yourcompany.struts.form.VideoUploadForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-18-2009
 * 
 * XDoclet definition:
 * @struts.action path="/videoUpload" name="videoUploadForm" scope="request" validate="true"
 */
public class VideoUploadAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		try{
			System.out.println(1);
			//ContentDescForm contentDescForm = (ContentDescForm) form;
			System.out.println(2);
			PrintWriter pw=null;
			try {
				System.out.println(3);
				pw=response.getWriter();
			} catch (IOException e) {
				e.printStackTrace();
			}
			
		System.out.println("Video upload action");
		VideoUploadForm videoUploadForm = (VideoUploadForm) form;
		//InputStream inputStream = request.getInputStream();
		
		String fileName=request.getParameter("fileName");
		String fileDesc=request.getParameter("fileDesc");
		
		/*ContentDescDao cdd=new ContentDescDao();
		boolean b=cdd.contentDesc(fileName, fileDesc);
		
		if(b){
			pw.print("success");
		}else
		pw.print("failure");*/
		
		ServletInputStream  servletInputStream= request.getInputStream();
		System.out.println("Servlet InputStream...");
		SimpleDateFormat sdf=new SimpleDateFormat("dd MMM yy hh mm ss");
		String fileLocation="video\\"+fileName+sdf.format(new Date())+".mp4";
		//File file=new File("..\\webapps\\CJ\\"+fileLocation);
		//file.createNewFile();
		//FileOutputStream fileOutputStream = new FileOutputStream("..\\Tomcat 5.0\\webapps\\CJ\\"+fileLocation);
		FileOutputStream fileOutputStream = new FileOutputStream("c:/videouploaded.3gpp");
		
		/*FileOutputStream fos1=new FileOutputStream("c:/3.txt");
		FileOutputStream fos2=new FileOutputStream("c:/4.mpeg4");
		FileOutputStream fos3=new FileOutputStream("c:/5.mp4");
		FileOutputStream fos4=new FileOutputStream("c:/6.3gp");*/
		
		System.out.println("FileoutputStream....");
		
		int i=0;
		while((i=servletInputStream.read())!=-1){
			//System.out.println("While Loop");
		fileOutputStream.write(i);
		//fos1.write(i);
		
		//System.out.println();
		
		}
		fileOutputStream.flush();
		/*fos1.flush();
		fos2.flush();
		fos3.flush();
		fos4.flush();*/
		
		System.out.println("Flushing...");
		fileOutputStream.close();
		/*fos1.close();
		fos2.close();
		fos3.close();
		fos4.close();*/
		
		System.out.println("CLosing flies..");
		
		
		System.out.print("files created successfully");
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}
}