/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.cj.bean.ContentViewBean;
import com.cj.dto.ContentDto;
import com.yourcompany.struts.form.ContentViewForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2009
 * 
 * XDoclet definition:
 * @struts.action path="/contentView" name="contentViewForm" input="/form/contentView.jsp" scope="request" validate="true"
 */
public class ContentViewAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward contentView(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		System.out.println("contentViewAction");
		PrintWriter pw=null;
		try {
			pw=response.getWriter();
		} catch (IOException e) {
			e.printStackTrace();
		}
		ArrayList<ContentDto> al=null;
		ContentViewForm contentViewForm = (ContentViewForm) form;
		String category=contentViewForm.getCategory();
		String contentType=contentViewForm.getContentType();
		
		System.out.println("contentType::::"+contentType);
		System.out.println("category::::"+category);
		
		ContentViewBean bean=new ContentViewBean();
		
		al=bean.ContentView(category.toLowerCase(), contentType.toLowerCase());
		String data = "";
		if(al!=null){
			
			for(ContentDto contentDto:al){
				String contentName = contentDto.getContentName();
				Date d = contentDto.getContentUploadDate();
				SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
				String uploadedDate = dateFormat.format(d);
				String path = contentDto.getContentPath();
				String contentDescription = contentDto.getContentDescription();
				System.out.println("there is something in al!!!"+contentDescription);
				data += contentName+"*"+uploadedDate+"*"+path+"*"+contentDescription+"$";
				
			}
		pw.print(data);
	}else
		pw.print("");
		return null;
	}
}