/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;
import java.io.IOException;
import java.io.PrintWriter;

import com.cj.bean.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-06-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/form/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
			LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
			PrintWriter pw=null;
			try {
				pw=response.getWriter();
			} catch (IOException e) {
				e.printStackTrace();
			}
			UserBean ub=new UserBean();
			String userId = loginForm.getUserId();
			String password = loginForm.getPassword();
			boolean b=ub.beanOper(userId, password);
			if(b)
			{
				pw.print("Valid UserDto");
			}else{
				pw.print("InValid UserDto");
			}
			
			
			
		return null;
	}
}