/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.cj.bean.UserBean;
import com.cj.dto.ContentDto;
import com.cj.dto.UserDto;
import com.yourcompany.struts.form.UserForm;


/** 
 * MyEclipse Struts
 * Creation date: 03-07-2009
 * 
 * XDoclet definition:
 * @struts.action path="/user" name="userForm" parameter="method" scope="request" validate="true"
 */
public class UserAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	public ActionForward register(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		 
		UserForm userForm = (UserForm) form;
		UserDto userDto = new UserDto();
		//ContentDto cd=new ContentDto();
		PrintWriter pw=null;
		try {
			pw=response.getWriter();
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		userDto.setUserName(userForm.getUserName());
		userDto.setMobileNumber(userForm.getMobileNumber());
		userDto.setGender(userForm.getGender());
		userDto.setEmailId(userForm.getEmailId());
		userDto.setAddress(userForm.getAddress());
		userDto.setCategoryList(userForm.getCategoryList());
		
		String categoryList = userForm.getCategoryList();
		
		String[] catArray =  categoryList.split(",");
		
		UserBean ub=new UserBean();
		boolean b=ub.register(userDto,catArray);
		if(b){
				pw.print("success");
		}else
			pw.print("failure");
			
		return null;
	}
	
}