/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2009
 * 
 * XDoclet definition:
 * @struts.form name="contentViewForm"
 */
public class ContentViewForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** contentType property */
	private String contentType;

	/** category property */
	private String category;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the contentType.
	 * @return String
	 */
	public String getContentType() {
		return contentType;
	}

	/** 
	 * Set the contentType.
	 * @param contentType The contentType to set
	 */
	public void setContentType(String contentId) {
		this.contentType = contentId;
	}

	/** 
	 * Returns the category.
	 * @return String
	 */
	public String getCategory() {
		return category;
	}

	/** 
	 * Set the category.
	 * @param category The category to set
	 */
	public void setCategory(String categoryId) {
		this.category = categoryId;
	}
}